# Generated by Django 5.0.7 on 2025-08-22 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('due_date', models.DateField()),
                ('questions', models.FileField(blank=True, help_text='PDF/Doc containing the questions.', null=True, upload_to='assignments/questions/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hidden', models.BooleanField(default=False, help_text='Whether this assignment is hidden from students/parents')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-release_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Not submitted'), (1, 'Submitted'), (2, 'Graded')], default=0)),
                ('score', models.FloatField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('first_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignmentapp.assignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('send_to_parents', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='assignmentapp.assignment')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_comments', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(blank=True, help_text='Optional: link this comment to a specific submission (grading comment).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='assignmentapp.assignmentsubmission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'File')], default='file', max_length=10)),
                ('blob', models.FileField(blank=True, help_text='Uploaded file (image/video/audio/pdf).', null=True, upload_to='submissions/%Y/%m/%d/')),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('transcode_status', models.CharField(blank=True, help_text='e.g., pending/success/failed (if you add processing).', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='assignmentapp.assignmentsubmission')),
            ],
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['release_date'], name='assignmenta_release_312850_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['due_date'], name='assignmenta_due_dat_8f4ea8_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['user', 'assignment'], name='assignmenta_user_id_7978f8_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['status'], name='assignmenta_status_ef6efc_idx'),
        ),
        migrations.AddConstraint(
            model_name='assignmentsubmission',
            constraint=models.UniqueConstraint(fields=('user', 'assignment'), name='uniq_user_assignment'),
        ),
        migrations.AddIndex(
            model_name='assignmentcomment',
            index=models.Index(fields=['assignment', 'created_at'], name='assignmenta_assignm_a6f3a6_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionattachment',
            index=models.Index(fields=['submission', 'kind'], name='assignmenta_submiss_f2c19b_idx'),
        ),
    ]
