# Generated by Django 5.0.7 on 2025-08-22 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignmentapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='first_submitted_at',
        ),
    ]
