# Generated by Django 5.0.7 on 2025-08-22 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignmentapp', '0002_remove_assignmentsubmission_first_submitted_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssignmentComment',
        ),
    ]
