# Generated by Django 5.0.7 on 2025-08-23 08:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignmentapp', '0003_delete_assignmentcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, help_text='Parents/users this assignment is assigned to. Leave empty to assign to all.', related_name='assigned_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
