# Generated by Django 5.0.7 on 2025-08-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignmentapp', '0004_assignment_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='points',
            field=models.IntegerField(default=10, help_text='Points awarded for completing this assignment'),
        ),
    ]
