# Generated by Django 5.0.7 on 2025-08-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_questionnaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='embedding_html',
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='google_form_link',
            field=models.URLField(help_text='Direct link to the Google Form', max_length=500),
        ),
    ]
