# Generated by Django 5.2.5 on 2025-08-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_children_name_user_parent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='children_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
