# Generated by Django 5.2.5 on 2025-08-22 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_school_alter_user_children_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='point',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='streak',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
