# Generated by Django 5.2.5 on 2025-08-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_point_user_streak'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='point',
            new_name='points',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='streak',
            new_name='streaks',
        ),
        migrations.AddField(
            model_name='user',
            name='last_submission',
            field=models.DateField(blank=True, null=True),
        ),
    ]
