# Generated by Django 5.2.5 on 2025-08-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_point_user_points_rename_streak_user_streaks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='weekly_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
