# Generated by Django 5.0.7 on 2025-08-24 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('posted', 'Posted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('content', models.TextField()),
                ('is_pinned', models.BooleanField(default=False, help_text='Pin this post to the top')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_pinned', '-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='forum/attachments/%Y/%m/%d/')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('pdf', 'PDF')], max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, help_text='Duration in milliseconds for videos', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('forum_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='forumapp.forum')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('comment_at', models.DateTimeField(auto_now_add=True)),
                ('comment_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_comments', to=settings.AUTH_USER_MODEL)),
                ('forum_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forumapp.forum')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='forumapp.forumcomment')),
            ],
            options={
                'ordering': ['comment_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('forum_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='forumapp.forum')),
                ('liked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='forum',
            index=models.Index(fields=['status', '-posted_at'], name='forumapp_fo_status_5b6254_idx'),
        ),
        migrations.AddIndex(
            model_name='forum',
            index=models.Index(fields=['posted_by'], name='forumapp_fo_posted__cc856f_idx'),
        ),
        migrations.AddIndex(
            model_name='forum',
            index=models.Index(fields=['is_pinned', '-posted_at'], name='forumapp_fo_is_pinn_bfee24_idx'),
        ),
        migrations.AddIndex(
            model_name='forumcomment',
            index=models.Index(fields=['forum_post', 'comment_at'], name='forumapp_fo_forum_p_cc0efc_idx'),
        ),
        migrations.AddIndex(
            model_name='forumcomment',
            index=models.Index(fields=['comment_from'], name='forumapp_fo_comment_6880ac_idx'),
        ),
        migrations.AddIndex(
            model_name='forumlike',
            index=models.Index(fields=['forum_post'], name='forumapp_fo_forum_p_5c3746_idx'),
        ),
        migrations.AddIndex(
            model_name='forumlike',
            index=models.Index(fields=['liked_by'], name='forumapp_fo_liked_b_8b26f9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='forumlike',
            unique_together={('forum_post', 'liked_by')},
        ),
    ]
