# Generated by Django 5.0.7 on 2025-08-24 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='updated_at',
        ),
    ]
